services:
  - type: web
    name: django-app
    env: docker
    plan: free
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-t@gb%h+l50yt0y=c1bausx1o&@uj$uu*y+6r_5y(a+zcwp&(y)  
      - key: DJANGO_DEBUG
        value: 'False'  
      - key: DJANGO_ALLOWED_HOSTS
        value: django-custom-permission-2.onrender.com,localhost  
    healthCheckPath: /

  - type: db
    name: postgres-db
    plan: free
    engine: postgres
    version: 14
    disk: 10GB
    envVars:
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
